---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  labels:
    app.kubernetes.io/name: postgres-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.2.31
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    postgresql: postgres
    role: primary