---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gluetun-sidecar
data:
  sidecar.yaml: |
    gluetun:
      image:
        repository: qmcgaw/gluetun
        tag: v3.40.1
      env:
        TZ: "${TZ:=Europe/London}"
        VPN_SERVICE_PROVIDER: "nordvpn"
        VPN_TYPE: "openvpn"
        OPENVPN_USER: "${NORDVPN_OPENVPN_USER}"
        OPENVPN_PASSWORD: "${NORDVPN_OPENVPN_PASSWORD}"
        SERVER_COUNTRIES: "Ireland"
        FIREWALL_OUTBOUND_SUBNETS: "10.42.0.0/16,10.43.0.0/16,10.1.2.0/24"
        FIREWALL_VPN_INPUT_PORTS: "80,443,${GLUETUN_FORWARDED_PORT:=50413}"
        HEALTH_VPN_DURATION_INITIAL: "30s"
        HEALTH_VPN_DURATION_ADDITION: "10s"
        LOG_LEVEL: "info"
        DOT: "off"
        BLOCK_MALICIOUS: "on"
        BLOCK_SURVEILLANCE: "on"
        BLOCK_ADS: "on"
        UNBLOCK: "netflix,disney,hulu,amazon-prime"
        HTTPPROXY: "on"
        HTTPPROXY_LOG: "on"
        HTTPPROXY_LISTENING_ADDRESS: ":8888"
        SHADOWSOCKS: "on"
        SHADOWSOCKS_LOG: "on"
        SHADOWSOCKS_LISTENING_ADDRESS: ":8388"
      envFrom:
        - secretRef:
            name: gluetun-secret
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
      probes:
        liveness:
          enabled: true
          custom: true
          spec:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
        readiness:
          enabled: true
          custom: true
          spec:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 512Mi