---
apiVersion: v1
kind: Service
metadata:
  name: redis-lb
  namespace: database
  labels:
    app.kubernetes.io/name: redis-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.2.32
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: master