# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:1kM1K+Mfsidpf25qIj0YwjTnwaLURjQkvrz3HGlo6C+mx2ms5m/tJw==,iv:XyK6NSmBp7S1NRIq2YKThlE1lzbnNE/ZfU6UWnBkPTs=,tag:R1Y17wC4HxOjo/pqRrPy1Q==,type:str]
sops:
  age:
    - recipient: age1gm4pzyutmqq4g38e32xjf2re7hq5m0nfuymstvwy3hp9xzgwkg7qu6vwc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZGhtd21CZmw3L09yYlBS
        RHMrbmxMdlNlaW1VS3k3RUNwTjFZL0RRUGpJClB0OUQwQzg4VDdyU3BSSHAzOWtP
        eXIvd3RMM2duUXhlazV0SHBSbW5pR1kKLS0tIGF1QjJlQTRVOXgrVFFvL3VTZ1ZF
        dHQzRHdVSVc0aUJrQ2loM0RLTDJIUncKOgw9PKOuPeXURa2+IhueGccNhgj/Mo5v
        AjqO7gWe++hzX7SW/NgU/7hqKDQObJNy4vtN3PKmFMtJT9tG2ZJyJQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-26T10:38:48Z"
  mac: ENC[AES256_GCM,data:lH68/xOOa9Zqb3LdcXGY1L7BNth9cVW8Pgid3xjXW7mCJIHVnlWTRvq/oFq8kztinGXusa2cRs2DahX9knt2LUpvKuT8fVVq+M/y3T8QQI0BwOXqRXyMbs5aCoENU1wY4DTfvTcjzYfIAKoj+lDSafwVZqoBMgVr19b++CDtR9k=,iv:0hZOk9ipH0X/VJUTmpFDi70+XsJFRRatvW2DYlbCaV0=,tag:yFp5W6on3bwzEXz1bi471g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
