# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:a5mh4wQFvNiMVunRZE4AUX63,iv:3ZV0UyfSLbdSFN3ZuTYCFN09lVDZ9F0kQfL6jWVVWdQ=,tag:hwLUcqaiuN3AcYngRLVKoQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:nKDLwLd39IdBFubXa9AUUXu6+wG/T73PBkF+Y305aeXf32ILUQ==,iv:v3X05OhjunqXvfI7Ith2LzEOZk5+buWW7kqq6jF4ii4=,tag:0gTgukImGrZ5rhsQz50Mtg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:PFlxbcZ6RXYt2uP1l62gm7I=,iv:ZlAOMB/XSSnpX0N70xILusVhNnKuLbjruSwuvGt7Fhw=,tag:1oR3d4siKkKTkidRck+7iQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qt57vy74f202l635kzz7dpv3d6k6mq0qpkcnvpsrz7yn46zvdfwqdwj3se
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bGZTTFBXcWNkaTdOTzhD
            S05jZ0JqVThub0NWeWNlTE5ndlpwK1ZhWWdrClE2NEdTNEF0ZHlGMzVtZ1o5aThG
            bG9JR09wdzBsK3FycTNxZEVrV0g4RFUKLS0tIGtna1I4R1Erb3pFVXR2STNzaW5i
            NDZDcS94ZkFkbUZXajRLc3lEZWZqbDgKy+FNVxZTJziyf6iIbuLEqxK6lt7ztHTm
            wDmX01co5ZVQHd8rvBZdF8Xr6emUbKvem1TcdqylNf+yOcxQtcPbmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-09T16:02:28Z"
    mac: ENC[AES256_GCM,data:kUu+ee7rxBt+dohChZULtzhwXuf1WoBcKkjv+IY9ILyhZmSCymwKDOsV6PVaSMQ5zGps3RpOj1dKzGqXdPdlyMj3FQFnXaWarE9TAVuT1XSffIJmtFaMoPKu3VGfSyhGUu6jlzSQTbBjERl+rmD3MVji/Z0fwVTOsARDYe9oalo=,iv:gRLMiAlIQqDOR/uz+PJieKDkrd5CU+cYxP3IJxDFUXU=,tag:9R/W+sCXzYSUUnufx97kVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
