# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Rix0eFmuD0+4eqHH7SFcaBWy,iv:SWSL85mGzsY4r+DUSTKkKJ14p3Syz4meAieMhtDTmTo=,tag:nuzxA4aDUjIyV7yueZF+Sw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:yxYR1C0p25rD1lJqHO2CfBcQd6e2fxg5+yaqStCx9eh16UhpQA==,iv:6EYrGU4gjc7iyeCFoHLM/gsGDiABndzhge33gma6tm4=,tag:TaV53EBFfKHjO+hiTt2FTw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:Q0BuyzFb7FhmV8EGk6KhIhw=,iv:VbvcCTsX20Z74xaXIfSHgEVooo7tfotInd1QTqS+Db8=,tag:A8Xku4UVQU4IMGz56lFYAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qt57vy74f202l635kzz7dpv3d6k6mq0qpkcnvpsrz7yn46zvdfwqdwj3se
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeVgrNlFnQVJaTVRFTDJt
            bDdyQjZOWTJYY3FNdTNvN3F0bTdQU21lWG5JCmVFQS9VbWNqK2p4dXdHVXZ2RHNL
            bXJxMmIwTUlvS1hubUNQUnRnZC9mdW8KLS0tIHMwallwNjMvN0MveUZuRWZOb0Nr
            VmRjM21XNTJqTlRQZC9BT3lla0dEUnMKEVLB+BLr8JLxuw67E4reouu7jwJHOU1o
            mB/02eMZQska+ltRwcyVK0Xy0qJgoXgkksldI+0954pbdu0q7ZBknA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-09T13:45:23Z"
    mac: ENC[AES256_GCM,data:NTe2e0z4UkLHqUHOczwzdKO6c1W3JZDrXRo9MxwJ1TgMCH/LM8BXioh4s85kYrWe3mll74fhWSu3DnOLtk4U0+T9RnIRl2tHCCaEPokWkOE0L/jlkdt8/PdDoEv6w1U/BHF90x1IZTE4794K+8eZ73nkyN12juaokOF1+uAeB+o=,iv:B5auATtDDyFwfj1JYdix96XF/XaylFajmqbHiLWkyYc=,tag:/I4eT58O4GC1ri5wko8DfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
