---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: maybe-secret
  namespace: default
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: maybe-secret
    template:
      type: Opaque
      data:
        SECRET_KEY_BASE: "{{ .SECRET_KEY_BASE }}"
        DATABASE_URL: "postgres://{{ .MAYBE_DB_USER }}:{{ .MAYBE_DB_PASS }}@postgres-rw.database.svc.cluster.local:5432/maybe"
  dataFrom:
    - extract:
        key: maybe