---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: maybe
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      maybe:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/maybe-finance/maybe
              tag: stable
            env:
              RAILS_ENV: production
              SECRET_KEY_BASE:
                valueFrom:
                  secretKeyRef:
                    name: maybe-secret
                    key: SECRET_KEY_BASE
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: maybe-secret
                    key: DATABASE_URL
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi

    service:
      app:
        ports:
          http:
            port: 3000

    route:
      app:
        hostnames:
          - maybe.npmulder.dev
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https