---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: maybe
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      maybe:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: ghcr.io/maybe-finance/maybe
              tag: stable
            env:
              RAILS_ENV: production
              SELF_HOSTED: "true"
              RAILS_FORCE_SSL: "false"
              RAILS_ASSUME_SSL: "false"
              SECRET_KEY_BASE:
                valueFrom:
                  secretKeyRef:
                    name: maybe-secret
                    key: SECRET_KEY_BASE
              DB_HOST: "postgres-rw.database.svc.cluster.local"
              DB_PORT: "5432"
              POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: maybe-secret
                    key: POSTGRES_USER
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: maybe-secret
                    key: POSTGRES_PASSWORD
              POSTGRES_DB:
                valueFrom:
                  secretKeyRef:
                    name: maybe-secret
                    key: POSTGRES_DB
              REDIS_URL: "redis://redis.database.svc.cluster.local:6379/1"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi

          worker:
            image:
              repository: ghcr.io/maybe-finance/maybe
              tag: stable
            command:
              - bundle
              - exec
              - sidekiq
            env:
              RAILS_ENV: production
              SELF_HOSTED: "true"
              RAILS_FORCE_SSL: "false"
              RAILS_ASSUME_SSL: "false"
              SECRET_KEY_BASE:
                valueFrom:
                  secretKeyRef:
                    name: maybe-secret
                    key: SECRET_KEY_BASE
              DB_HOST: "postgres-rw.database.svc.cluster.local"
              DB_PORT: "5432"
              POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: maybe-secret
                    key: POSTGRES_USER
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: maybe-secret
                    key: POSTGRES_PASSWORD
              POSTGRES_DB:
                valueFrom:
                  secretKeyRef:
                    name: maybe-secret
                    key: POSTGRES_DB
              REDIS_URL: "redis://redis.database.svc.cluster.local:6379/1"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                cpu: 200m
                memory: 256Mi

    service:
      app:
        ports:
          http:
            port: 3000

    persistence:
      data:
        type: persistentVolumeClaim
        size: 5Gi
        accessMode: ReadWriteOnce
        storageClass: openebs-hostpath
        advancedMounts:
          maybe:
            app:
              - path: /rails/storage

    route:
      app:
        hostnames:
          - maybe.npmulder.dev
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https