---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ollama
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      ollama:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/ollama/ollama
              tag: 0.5.7
            env:
              OLLAMA_HOST: 0.0.0.0
              OLLAMA_PORT: &port 11434
              OLLAMA_ORIGINS: "*"
              OLLAMA_MODELS: /home/ollama/.ollama/models
              OLLAMA_KEEP_ALIVE: 24h
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 5
                  timeoutSeconds: 10
                  failureThreshold: 60
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 500m
                memory: 1Gi
                intel.com/xe: 1
              limits:
                memory: 8Gi
                intel.com/xe: 1
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: ollama
        ports:
          http:
            port: *port
    route:
      app:
        hostnames: ["{{ .Release.Name }}.npmulder.dev"]
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
    persistence:
      ollama:
        enabled: true
        size: 32Gi
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /home/ollama/.ollama
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp