apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:x5mvEEAZq/VyYeQ8BSC8tuhP6c4vXMyHwEeVFV7sI7aG2KRYjnYJQg==,iv:l7MEeGa11XAjysZk2sMJHM0M8vaE3N4vUOQkM3nrtlA=,tag:YgYEOmA8SrtrrRgvUqv3VQ==,type:str]
sops:
  age:
    - recipient: age1sg9gnvhpvlw3r7t8yey6x73w67pgsfpjd9884k773pzm72g3r39qvwq20v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTHhhaW9UWS9SVy9Tb0Na
        Z05NMnRJU2xQek9yUTlNRU1rWGFKL0ZtbUU4ClhGSTliaXpueU1Oc2k1dE9EVFhK
        R1dXUFJjQTNKU0lITEp6WmJlcGp6MlkKLS0tIDlzYVZlRFV4TWpMLzJ4a0MwL0pF
        QnpGbmh5WkwzVVpGR1dBSTh0R01acTgKINRf51QEGqEW+azQRy9beZEUMCldsFah
        fBD1uTE2BBv6x1dsIIkY/Ms9AjlUPYe+jd0iGS7fBCGZcWAChrXQfA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T09:16:42Z"
  mac: ENC[AES256_GCM,data:NroS7HJm7f4Sxo1tpHcrcC8kaPzD0LKiTtb0U0i4aw0UT0IVeoV9lJQ/dEkNfa9D7uUm92UQ9vrIWMq3JGDmDYtzVBk91Tm2MY9z4HixZ2jgbTWQli6+J7ooYYPjWoJ8g7gocd1egB7lqWO7vdiU/Ty+wMGbjPPP1H1yRvYdhH8=,iv:NZPpcaa/90BAQI4p5JPtElUuFA1IGhjDMuVmvokqrWQ=,tag:Ub8xuefPRaUEMfxzTVB6PA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
