apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:bsFMhwZGTzU+vmMb0YGqGxQNAmr3GBKhkUMWtfsL5PnfbrUbDWL1sg==,iv:TVqi9noyDazk1uSy0Tx79lFnHtPmqeRA1uN2hT4Yz8A=,tag:wA4dTJn7qVHKM0WUNygDRQ==,type:str]
sops:
  age:
    - recipient: age1sg9gnvhpvlw3r7t8yey6x73w67pgsfpjd9884k773pzm72g3r39qvwq20v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUEExbFEwNHVxUVNUWThk
        ZjhHaTZld1Z3R3ArMGhJdU1nMWxsWXFtbENjCkhsZXFPcnZ2dnlWSjBPeXhHb254
        ank0eDV2eEJjaVBxdE05V1JKRXJVaTgKLS0tIDR0N3hjYU5XVkRZbjR2L1Bhd3pi
        R1VPZ3V0WVo3dnU0YU9QYk5FQnVKMGMKqPW4KrVjsjRsJbRUabPC1OGVgNF9Q5gI
        5QbLKkL54CHMY3sa/4kpTyl+rlJ1Dy1ti05KFbFIcWRu35cEbTJGhA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T17:49:58Z"
  mac: ENC[AES256_GCM,data:UflP/gXxQ72Jleua4BsT6VIOBTBIuyqqWxLwsSI7gsj14CyN5GRQxxlEj8CO0uH56KIr+k+xjri17QM0XxpST1A3b/PVvjTZCuEzMtb7a7HsP0PcB8j2hZQbxnygW8OT72ilMk3cp83BaKUrayeKh7zdYnniUTv3EiElxevOPk4=,iv:4LGHMr+1BUoLetKaCuPz8BxSB9+wQHv4W5358sz3rLY=,tag:Mb/ignS+2k9AtpeXqEMqPA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
