---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/deviceplugin.intel.com/gpudeviceplugin_v1.json
apiVersion: deviceplugin.intel.com/v1
kind: GpuDevicePlugin
metadata:
  name: intel-gpu-plugin
spec:
  # Image configuration
  image: intel/intel-gpu-plugin:0.30.0
  
  # Node selector to run only on GPU nodes
  nodeSelector:
    kubernetes.io/hostname: talos-cp-01
  
  # Enable monitoring and verbose logging
  enableMonitoring: true
  logLevel: 2
  sharedDevNum: 10