---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: intel-device-plugins
spec:
  interval: 5m
  url: https://intel.github.io/helm-charts
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-gpu-device-plugin
spec:
  interval: 1h
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: 0.30.0
      sourceRef:
        kind: HelmRepository
        name: intel-device-plugins
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # Intel Device Plugins Operator configuration
    operator:
      repository: intel/intel-deviceplugin-operator
      tag: v0.30.0
    
    # Enable GPU device plugin via operator
    gpuDevicePlugin:
      enabled: true
      name: intel-gpu-device-plugin
      image:
        repository: intel/intel-gpu-plugin
        tag: 0.30.0
      
      # Node selector to run only on GPU nodes  
      nodeSelector:
        kubernetes.io/hostname: talos-cp-01
      
      # Tolerations for GPU node taint
      tolerations:
        - key: intel.com/gpu
          operator: Equal
          value: present
          effect: NoSchedule
      
      # Resource configuration
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      
      # Security context
      securityContext:
        privileged: true
      
      # Device plugin configuration
      args:
        - "-v=2"
        - "-shared-dev-num=10"
        - "-enable-monitoring"