apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ZZxIy3pcTPtn,iv:3WWTSzjS76f2h75LawjPJQQ5foKyDHMNEG8BKDIlPoU=,tag:VO2NNcYeZV+Imjoew4hi9A==,type:str]
sops:
  age:
    - recipient: age1sg9gnvhpvlw3r7t8yey6x73w67pgsfpjd9884k773pzm72g3r39qvwq20v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Uis0K0IzbmFhUzJydVpx
        eldlbjliazBseGEwZXB0aTNyZTJXWHlzMjFrCi9lMEdZWmpYSXptVm4waUN5Wnp3
        bXhxZHgvTkF4N0dhaFRKMGVtOXZhMUEKLS0tIEw1eFBaYWVmcnliVTFYWFN0OHRN
        S2tJQmxTQkhMcm02TEZTOVZZVDdPK28KEf4TbqQ6XoFXwGILmxzhF1/hDcdwuB8r
        4OjplQ6+EDW/OzATUp9JW7rAl32VgRCG8vv3pzO67s/2x7yrcLB6FQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T17:49:58Z"
  mac: ENC[AES256_GCM,data:hUkdf22aBR/NPwqx9ecMz9M3LuxeJSvppyv+jqfLbj427ezfuJlFBEIx8VrqKxAzgKCexm9QXarQoVhS4VjFwCxguhQv3HwX34850VfuPa7dF4RADH21jtSrS91woIrCMhfBCVGvk0q0qhwc/0NL1xKb0VZvg6T4X9h8JSf/+0k=,iv:XKsT1jJ02jE7akb0z/LvpLkyosqMQe5oKgSmljS4yAE=,tag:rMYm4mTpo+HGAseLXbrK8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
