apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:NaQaDHGupA3S,iv:LnT/vR/f+RcJH6S51amzKvIXOYv49HlswX9mr8EPWDw=,tag:n/CSB0LT7Bumb8WLEt/hSA==,type:str]
sops:
  age:
    - recipient: age1sg9gnvhpvlw3r7t8yey6x73w67pgsfpjd9884k773pzm72g3r39qvwq20v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVS9USUlpVnlGcnFwbWFm
        eHJVR0NNY3UwUTY2bTArK2IyVk1naVd2VDFZCkJQMXYzNFJJMG41T3kzQktiV05T
        QVZ3WmN4d1ZZSGRleXpWcTV4UlBuZE0KLS0tIDBLSWFROWxHWGhkZ1hIdFFHdkxS
        cktURmVnUWltVXR3NHo4L3hrd0laeXcKQffizkvwkP5t+N0S7jcu8YAGesPkrncV
        l10MxVADavWhpWgPfONbBXVghTNh+h0DMqAiNHQICZPOFvVrfRVwJw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T09:16:42Z"
  mac: ENC[AES256_GCM,data:i2v0e2uI3wHKcXYBRcQyxYbFAwx8NNjOCGgIHKCk84gGdJqZLL/9Pb62LnweK0blfejwXrw0Em+9tDA4s/c2gCH9H4sunKh7XwIwkOCyeaY+uwi3l5bsUZ6jvCZ/cucqA5HWHZJ2yaD4cgnYnuQq2HaUY57XyHiNDMAQ9ufrmXA=,iv:O2DjDRvdD0KrX3FnnxOeKlfiRG9u0SdN89lzrQ3fbuI=,tag:xhGs9/4q5QJW6taHvouOPg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
