# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:72mf2kHf5G8N3w2trOGKgj5O,iv:L/B+dZzeRUe1gavzGQS34y8iy4gz5NOUVY4vCY190WM=,tag:Vn7JQRCqOMuXWqvkpKNVwA==,type:str]
    api-key: ENC[AES256_GCM,data:DYjD+l+LC7Z5KdwdSYJmfiWoxMr9dcBUdizSDeB8pNPtAHWTgQ==,iv:LF7zwoyWAleH8qxI74DiOMIzshKoaySan8NpiZNtZEs=,tag:spEZz7LGO45sYIOiDByQRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qt57vy74f202l635kzz7dpv3d6k6mq0qpkcnvpsrz7yn46zvdfwqdwj3se
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTWR5emhPc0tNblZ4aE14
            T243QjBmYjhXWndxd0VES2gzS1U5di9rRHpnCkNaOVlQUVFGSllsODA2M1VFWVpB
            SktocWV0Vk52YTF2U1hnbXI2WHMyOTAKLS0tIFFyRnQyZDY5NzRYUVFtYnZITXMz
            anhDeEVvMkZENisvbGMwckJ5bis0V1EKSNWms7PtPpQCMrxEFo6hvYEi8jp1xquh
            nlfpRGQaEiyd/H02fvxCB02bWX422jeBEZdN3Vs/xMQsfCcuFWTdCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-09T16:02:28Z"
    mac: ENC[AES256_GCM,data:BnuZDNEy3aIzcZkSM4lUhMw1Ml9o8qfa0PjtyfU5EtWbqwSCeoJwyIeTPK4cGPjR2KAHd7JQsw9sgeXcfwZbmvDMlOEWRP0Cj1ZuWWg3doepEfaFPBTMpINJLrIFUO7SStQ8d5UasXQuN/4a1jQBjROW9iTdJhgP7bfFMgFecB0=,iv:l33SazjMUq4ECNHkttm83l3lFEx9wBvYFKP3QxmyvOw=,tag:XWCvbbhh0zaVSJV1+uCgvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
