# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:mhtfHwRQtQIURB2FQCyNeR5K,iv:UQHy4nJvq/mOWu0xw+TKcJRY2RkkpbjeMze3o9EPUt8=,tag:GCOjA7x+AzLbPvw5+r3Wkw==,type:str]
    api-key: ENC[AES256_GCM,data:WD0PUI6L4Asdnqe/1clENKaOaeFan1ajcCkrkOG4/JHiLf77BA==,iv:StMDm38FwcqxFvK3z9gi5fZQ3hn/9BnkKqd27tznde0=,tag:aZ1R1OVPdIMOdbgIDOdtvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qt57vy74f202l635kzz7dpv3d6k6mq0qpkcnvpsrz7yn46zvdfwqdwj3se
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeEZidm0zaWlaQTlJVlh3
            Zk9FbWlKMC9ZZDVVcnZGbnppeGpoVmY1VkRBCnhjeTNiQlN0dXFoNWFSUERRVlBF
            V2picU9BRllLeGwvMU93eDNrVUg2ak0KLS0tIHpSVFZsZWlVUzVCWmR3L2F4V3hs
            L2FyZ3BZRldTMENDKzQvSDhqeE5LTWMK63yfFDBaUqhqNbVn/SepT2PZNO/5zn0h
            sq1VQrTijwPySk80rGVknes367WandzehNv6z4LC4K2NBltunT6+SQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-09T13:45:23Z"
    mac: ENC[AES256_GCM,data:+07DnAXZKTjY0ZpH47QVCbM70oueIXjiydaTkOJBhSa5RdCs4wyPdN3GXuJHoWQsWHVbO/ZR4hdJ/fl8O3wMXt8UZptSVm7B86a+OHHWsNXAaK/uJppSYWEIAjoXnidUrHR/dSWLAcYkFCou5iwdy8tha3wmdeWDgLXoTLsFLeA=,iv:QaBvmQI6FvGIMr70P0TZdDrXWvxhdSMmQ9YJfPyTmHo=,tag:57JVZEIQWPM2d+5XH8xy6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
