# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ""
sops:
  age:
    - recipient: age1gm4pzyutmqq4g38e32xjf2re7hq5m0nfuymstvwy3hp9xzgwkg7qu6vwc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWWxTckpMMy94b3pYU0tM
        QytTTkhibUtzRFRNQ1hNVXpTU0VBZDlpalZjCm5XYXZEaGJFWnFucWlncThvc2N3
        WWRxVTl3Q1VBWG51WUlXTTlmMW1BaXMKLS0tIHFGK2VHSDdORzRRU25BSGZCekdq
        MEZZWUZYbHJyMFZlK01SUGNXSktvWDQKTQgLSl2m5AgQbr4uirkR4ZYPbzY+dF62
        U7/8CM7UwSnsYyluLLGsCCB8P08boejH1dYo2pZccfLkmyp8RC/adQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-26T10:49:48Z"
  mac: ENC[AES256_GCM,data:Tn7FuOlSOdAZz0eV91IOOPpaCfjr2jBfe54uPAKkdeFc7Ta5NPNP3AW52QYt3Hpn3bXXxCPVaktAdHCt39aqvj+aAf/6IcG/0TIVyhxAbulj/T12TqedteLd3M5DKAGdwZLKWuLX6hmgkyqV7Q6oq0WsbiyLK33nhsNnAOcD9YE=,iv:RhtF1TQSR6ziub8qgtIoJKWxGCKeDNOW6i9Dfrz+zDw=,tag:2xCVDf0QrUAVWKR7tTrniw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
