# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ""
sops:
  age:
    - recipient: age1gm4pzyutmqq4g38e32xjf2re7hq5m0nfuymstvwy3hp9xzgwkg7qu6vwc7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLamZvNmVXOVhKL3BHbWlV
        TG82dEdlQzZELzVFRFltd2xHTHhJbzRGTFI4ClY4VzZvMkNsOWR6c0h3MkN0ZnMv
        b1F1SjBWQ3dOOEYvRVB0RVA0dFMzR0UKLS0tIG1ZTFZVUjR4VEJMZmhTZWZzWkNW
        VkY0bVExVGV4Q0tFdjhjU2pmZ2R1MEUK43aL1mMvjqPesqirGYeFodGUQoQTy6G3
        OAqi3Swvuq19ecwEgn8lzvCeaFBdYNlRh1oS/vKnypRhv30fo+7ODw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-26T10:38:47Z"
  mac: ENC[AES256_GCM,data:1y2kPgFSRVPZlMOeXiH8NDZB2b4+JjCIBjo9ssfBKeNYUQaDdyH3JgjnYA594JoQTOBcVg3BTFunl5Q2W41VIuRSiEXmknorQkdhQPVzjsvLD/fbs3TCwznwzS3wvfUdqr5Ck8+98vYTry2QsN7SSmgVDusX/WsuhFF10g5+dXg=,iv:DabApyFVdQidqqpMFG4J9JHFrZPa6zXByOfGGGb8RJM=,tag:j9d7KN043hRV4HYigekT2w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
