apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:6+Pvjuevb+mYZyYPOZ+VtyRm8IY59XfcHAij0Hp/7QY=,iv:4ayNQlLxU1j3pxGH/dnVqF86Nz5oViqkeCDvQuAEJHU=,tag:4Us6yUMduOpoptx0SePeCg==,type:str]
sops:
  age:
    - recipient: age1sg9gnvhpvlw3r7t8yey6x73w67pgsfpjd9884k773pzm72g3r39qvwq20v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUmFmVS9PYmRja2M2SXhF
        WVAyWVcvaFgyRGF5dmw5cU9tV3pueTlDL2lrCjloZm8rWU0rTEFQQnhQTXEvcGZi
        Wmc2UHJCcXB4TWFsakZEN1BpaWdjcG8KLS0tIDJ3eTFSYTA5MlhWSE01K1dBdmJI
        RE5KOERpR2dEbllGTUdmelhVK1dOdVUK5miJvlyeh2VO+x8GvHS5jBHKRY/Yjm8/
        0CzOh4xfRCzLeAwy3J5zL2ptUniO0Uql8nxnpJ9QvW/+AifgIDcEOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T09:16:42Z"
  mac: ENC[AES256_GCM,data:Fcoc8wNMpB6Gt9cgjcHST6FeKUBjA77lwPPj35huKhI/7dlPZWL38sIUZjIdiZU3eL2Qr6gCGctmjR+3OjtENFSfh3VOlB08SQcq4viwgj/T1TTmQZNr/QRlAdr/SZH1V11oi8o8/jZs7aYY6FnRjs5fnthHD99WhrAzOVyeoF4=,iv:qX/t5lDTnClWCp6jVGZqmFrqcWcNXrwHIQCtxGWJaw0=,tag:imR6aj9f2YUHu0+Bz6yKdQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
