apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:fMx+pn6um8gENPZF1HeDctLYsO0XIzpa0bYIgzomOH0=,iv:VSyNJUE7ATnch2tXWcEt0zwkepE6OMFx6YeinbOqruE=,tag:Xnn1xFRvo4NLfs2xwq0TxA==,type:str]
sops:
  age:
    - recipient: age1sg9gnvhpvlw3r7t8yey6x73w67pgsfpjd9884k773pzm72g3r39qvwq20v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZlFzQkdTZjhhQW9aVVNZ
        L2w0eXE5dzVaMllBQ2ZPT1NPS04xWFEvUkJJCnFucDVLUmN4RWxpK010R2RLTnFY
        RnhDVFFxWkJoQW1UbHFBSXVhc1Y1Z1kKLS0tIFNid2pzTDJCYVpRNzZOWGhpcy9u
        akhBTkVHZ0VlcE13SkZjZStRUENJam8KpeHwrjsrCAJNEn4WGcxIKq2+CASlVOjC
        NQeCO3g8OB6J/zuExMmb//KomCBMyZep7RLznuFzcdWNrau55YEqkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T17:49:58Z"
  mac: ENC[AES256_GCM,data:kyoEFKUVz6JygahjuE1SLCCKjkHrrbTmZLCT3ItGWVkObp4vh9fqpZG42rDSyzujWqXxwhjehVmKvIQUISfCHZac/k3Np5frcednDymVL1FygslgzuMpnerI3YLLhrtdoSlI3mwBtekreyjR35MNYMpBXU9pf9f19EX9ZuPvRsc=,iv:bv+nhRaaMbtUuYWTPpj7zFsW53GICUVRjWTlR1WFa5o=,tag:xmPfMlZrNRSgZY24RtWOew==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
