---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: resume-api-secret
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: resume-api-secret
    template:
      engineVersion: v2
      data:
        RESUME_API_DATABASE_USER: "{{ .RESUME_API_DB_USER }}"
        RESUME_API_DATABASE_PASSWORD: "{{ .RESUME_API_DB_PASS }}"
        RESUME_API_REDIS_PASSWORD: ""
  dataFrom:
    - extract:
        key: resume-api