---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: o11y

components:
  - ../../components/alerts
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./grafana/ks.yaml
  - ./prometheus-adapter/ks.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./victoria-logs/ks.yaml
  - ./victoria-metrics/ks.yaml