kind: Secret
ansible_user: ENC[AES256_GCM,data:kg5T3g==,iv:XmskQ4qy5yeBsrhY0bfK3Uyx8KCf+tQwbWXs4LfNmgw=,tag:WQiUz+b7/hW5ZW97kKtxqg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:TN4y5tkiy60=,iv:nqIOV94aV++mNHU009QT1ANXgJG6kN48aMDpnUcZ7VA=,tag:HWWDtNkQaC0pH6oq6Zuq0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qt57vy74f202l635kzz7dpv3d6k6mq0qpkcnvpsrz7yn46zvdfwqdwj3se
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY290WVV6MU9NYlZlbVJG
            K0V1ZDJZR3BnTmQ5OXlpN251bCtWNWI0NUg0CkI0bEQ5bGhnaHpOTjRNbk1DYWxV
            eTFiMWpvMTFWT21sUkxYU0hHRWE3Qm8KLS0tIDdUVkhFY2puR0VwUEtjMFgwNllp
            N3dDaXpYd1ZLL3M0Z2lXZmszOFFBNFUKVQPFIQcQQBsYMd+J5NFBgtAVLLIrQpYa
            IhF6kZ1IMjjD5wRDMjqkc0+hPS76/JyUATfM8dBxdDB5BIUB11qRUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-09T16:02:28Z"
    mac: ENC[AES256_GCM,data:kOpu1HpZ997STsh2mKwQKxu2r+nx0RmbEGKm5ByL/88lIFaqo5smWCJJSvIhP/5RBSkivuNC+tiRPZ+RFtUKbcTiZ5fOIhZu4/a8ozG5avx/7evt5IW2DwxB1a9ZXubdsGnr0BqqflGtoAp4GiJK+aEZjWgegl7OE+UN/z3EQu4=,iv:0F5Ld7AlLhs2dj/iWJfBfm5xVXMmDABgPHATaQio82o=,tag:N9oNXn7lgrdmpIVeoJlxDg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
