# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:gQjYOV9FnqXCa9YB,iv:qlLklQ19DbE9QHwgBwhffoljAStl/htR7h48A6HB2Lc=,tag:N+lpxO1dICVShF2UWz2SVw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:TYFmbtpx6i8LdiFESp2IXkHq,iv:/hnn25gy+eJD12g77tryEin1N7P7xbZAbyfGj94bg4w=,tag:bwfhsQlisJ5pplznjsyqbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qt57vy74f202l635kzz7dpv3d6k6mq0qpkcnvpsrz7yn46zvdfwqdwj3se
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWXRmaTV0QUFCeENNNjBw
            bUlLYnMwVG9RbVhCMFlzWWdBTytSRG1xZUZnCnJ5RWZWMkpyVlpNdG5XcWtsVXJt
            LzhSaGsvbXRBZXF4TTNJNDdjVWNoSmMKLS0tIDRmbVpzT0R1WlIwOFBiTVRNcmFE
            RnRZYmE1SzVldTR4SkVPdkMyVnJxODgK0jYau0NlgIm54u1TYagKZwLZXdATLjTh
            usBzBWo2gap47B6SvnKbCQ8CPshZamK6DHf1cygib2FzqyT1E5lP+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-09T16:02:28Z"
    mac: ENC[AES256_GCM,data:POP3ZvNVcydkfmp+drebJaKQa6B+CTP1SqVsz9RIFX52/mwTs3D/9JR0VGWCkg/uu5PHH5ov12PAPJZ6KOb+n4fJ6t0770iwRBUn6Z/R0Sprs4C3fRbqC2Kk/WDOSnP83nMXbydNbTWKTqXRSG6F9O/+duksLOHiJ97676W9ajY=,iv:oGm1Qpxkin7avLVmM0bXLZXt9PwogGVni6D/t+NOHvI=,tag:FYjhfuF172afTpI49AogHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
