# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:NFHkXGJmuhE1Y0nV,iv:HWzR9reh7lWig06mpEYcHQW2rS+VpfyTeKnm/Ix4m2c=,tag:BnSHvlrlFT/TfxHqqoOAAg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:DvY/kjbEpYXBxE2XtI0kHT+z,iv:ui/h3KJENYd72ACeBNV2dM9Sk1x8M/VV/RNKLO+Suzs=,tag:GpVveF1fX+UfTY6wBRTJBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qt57vy74f202l635kzz7dpv3d6k6mq0qpkcnvpsrz7yn46zvdfwqdwj3se
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMFpINi9IdVp2amxQTnc2
            WldYcXdESlE0TTJldXdaT1l5T1JtYi8zYkE4Cm9EUlRTTVN5YmsxNXI4V3ZBUFFD
            TEwzT3RCVzlrcEpVTWRyL3hNUExoMTQKLS0tIC9SaUhNMWtqWG1KWEd3bS9ZZ1Jn
            WHpTWXFPKy9WMzRDYXFLRjNLZEZBbVkKO16EZLzpL9JLJqDJ10ByJBKlQZlR+ev9
            pK+b7pMlajEoxKVvBpjngImqzABHfYsT1RqcBdlKaUSZNKRHj+ZQXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-09T13:45:23Z"
    mac: ENC[AES256_GCM,data:YV9QgVNloEpgSlAGd6iESqdg60/yngZQaLhs/zLZL/PP6OZIG13i+h2jB62JldGGlNsGuacdceRcxM6chEzGfYMEg+6ySAVhOHcALHnbD3GrqfPwfb51ArBapAgg3JLJOkIFlsf3zbNPl03JpfxxXz9H7TaI9lGscEgXUXpR1J8=,iv:48J7eKOglwKKrkCqDoqfejs04CL198U9SLAiyKSkP6s=,tag:k+1FVPkRR96lXIPJGPeNjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
