---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.1.2.210-10.1.2.219
  METALLB_K8S_GATEWAY_ADDR: 10.1.2.210
  METALLB_TRAEFIK_ADDR: 10.1.2.211
