apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:whBZGPhBwWuV2QXgWYpgi8KCgIMfdwQzqXY94qpLntC/+8oC8yCodGFKpM9937mCTu4+gcEeM5Pa/+qoTGo3SeTDysYNVswpmTPD1KTRT9f5W5FGeDd2tCElX+3CIAdD+yKD809S4R8jEM5MJmU5guyoD9k4zyDBVxm0Tz4xv+qln4MJEAUbWuAA6L2wdE4nkDBb+eLMsoFNswsl5E+HHB6apIiGYm5oQaRxG4CjM3UQ3ETK,iv:ALrRKu1vAZtXRX36ZheQzF2yaXbGK2ooOY7mtQVyoGo=,tag:Rm2n62lZKGQxZYZT/XeBXA==,type:str]
sops:
  age:
    - recipient: age1sg9gnvhpvlw3r7t8yey6x73w67pgsfpjd9884k773pzm72g3r39qvwq20v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYytHWmxFY3ZieUlpZmFW
        cDdyZHN4RXQwaTRHdHk0TnpPeWIwV2VQbVhrCmhjT2JVbmJVZWdzUWk1bDdJVEFF
        amE1eXQrL0ZIcy9lSHAvV0Y3dW56NVkKLS0tIG80b21XU0lOTGxpOWNXNStmc0d1
        OE8wS20vNUVNOWZnSCtraTIzWjl5dVEKmptndDZDgh7Po8aduYUP21nDpNZIrwdM
        LGb5uvFZKEWuxLQfvXlmNpKQVLwwwtxoozM5vdD1FuGiMnphPlc+Tg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T17:49:58Z"
  mac: ENC[AES256_GCM,data:Jwxei4W1TNyJpQN0rcLhuXbdUj4DDYGWiBpmb7Y7YGaEvLYtTQgTS+G+BbtvMygzC5nEMxPydzXfouMLNbXeTQkzgWZuPza9jqXhvqEYhq7qZ0mA0sOMpx+BpxW82TmZ8Cc8dpjJ4gWDmgAZ3H6VZddxEtPMy7iAidZe7kvBhLM=,iv:5QOqmiRDKXWtVdN7ZYIVGWFK3XgiI28LTYs4BvuLRhE=,tag:3aDJTQp3tjCJQNT5A5nZfw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
