apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:EHSUByhiFUFtWjHzUr3ULvEpOkWm5U+m6lzB2ZoZWEIAl1G898q5XA3dS3Y4W71NX2YmtPtNgVPqZBRooEw0utEUK301Wj6is6voJcEexwrzXyQ2K83lPpXoqNVmcr2wqcEaE4YDzfDL2gtl5VH19tsTgvi/d/F44Ta3ruaXC/31AunOdkDeCEiwyrm+VNnqQwhaKIH/Ssu4/4YKhwqixWj2fPvfFUUqbYbvmaI1lEoO00iL,iv:Y5AQAg7RpMBz/gYqmjfbyeXrMQ3K0WREbBEYfELcVjQ=,tag:Ctk64iJqui6IdkcIgPt91w==,type:str]
sops:
  age:
    - recipient: age1sg9gnvhpvlw3r7t8yey6x73w67pgsfpjd9884k773pzm72g3r39qvwq20v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cVhmV1d2ZHlENzh6VENN
        VUJoUHd5ZUtlMlNJODFTZDZZaHduRUhQakhZClRiaXJ2dFJQQkxMNmE4Wkg1TGdn
        Q3kyVnRmb3hORzJqeVZpVTIwUDZRM3cKLS0tIDhBK1NaaTVTVXVqY0ZlWWpOeGg0
        NDYyVnU3OTdVeVpGWUkzQ1I1enFYVzAKCmu/EXjYELVOcyRv4UqQcyOwvlb79FZj
        fL2kQipfK/9CTKJWWQ3jBX3L+vSB8ks0zizHlnx7ZEAHCOCXyOxFYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T09:16:42Z"
  mac: ENC[AES256_GCM,data:YnXOPkWds7la7EFE4U7HLmK02Gu0uWw5txuFPl7GL2MZp1N1sUj6T5zq8eWXsr5AXl8nL0YMn98RoYr/fxhOM5JLw6fBEQsZq+rcxHi1+/Pkh6hr+J8cQB0xw9lOuML5NwoDZ3Dv+RjOMLwCRzXPgt+//zEL8Jg4I5ov/KM4Sak=,iv:eSQMG1/mPrw+nQuTDVAjdLWwikVmTMLcgtuukx88AFk=,tag:DOEpzzmFpiwz8KrINIhbKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
