---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: internal-dns
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.16.1
  url: oci://ghcr.io/home-operations/charts-mirror/external-dns
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app internal-dns
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: internal-dns
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      repository: gcr.io/k8s-staging-external-dns/external-dns
      tag: v20250402-v0.16.1-48-g1efdf416   # CI build that includes Pi‑hole‑v6 support
      pullPolicy: IfNotPresent
    fullnameOverride: *app
    provider:
      name: pihole
    extraArgs:
      - --gateway-name=internal
      # Pihole only supports A/AAAA/CNAME records so there is no mechanism to track ownership.
      # You don't need to set this flag, but if you leave it unset, you will receive warning
      # logs when ExternalDNS attempts to create TXT records.
      # IMPORTANT: If you have records that you manage manually in Pi-hole, set
      # the policy to upsert-only so they do not get deleted.
      # Switch to pihole V6 API
      # Change this to the actual address of your Pi-hole web server
      - --pihole-server=http://10.1.2.5
      - --pihole-tls-skip-verify
      - --pihole-api-version=6
    triggerLoopOnEvent: true
    policy: upsert-only
    sources: ["crd", "gateway-httproute"]
    txtOwnerId: default
    txtPrefix: k8s.
    logLevel: debug
    registry: noop
    domainFilters: ["npmulder.dev"]
    serviceMonitor:
      enabled: true

