---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: postgres-backup
spec:
  cluster:
    name: postgres
  target: prefer-standby
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-backup-schedule
spec:
  schedule: "0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: postgres
  target: prefer-standby
  method: barmanObjectStore
  immediate: false