---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: resume
components:
  - ../../components/common
resources:
  - ./resume-api/ks.yaml
  - ./resume-website/ks.yaml