apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:2Vkvi4Iv+IuYA7TQbkALst5YiA1OnjXoojYciTudVMcS5DbsVAkoOQ==,iv:JR2K7W+QqMoYUNBWcSyZ6tJ1Cx299e/7LexZzZxXy1I=,tag:tnUY+YWqqhrt4vBUJU0+ag==,type:str]
sops:
  age:
    - recipient: age1sg9gnvhpvlw3r7t8yey6x73w67pgsfpjd9884k773pzm72g3r39qvwq20v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVnErOVJrSXNka2lQVXZF
        MEFvTk03eUJBbVRObHpmNlNBckVvQUZaWWp3CjY3V0RaandBK1RyMjA5bGJ1aXVs
        OVg4WkxKemFiRy8wcXpBenBOME9rWW8KLS0tIHhyK1RqR21pZldpQ0pnQWFvelpj
        MlhwNGpVRkxzRHhLOVVKaCt2RTBGNDQKuscsyLUh19M2loVFfm4vzsNAMWAcwnnV
        gxPfE64LQeUFK1Mdw1ceoS+kNk4z8p5ufjUgcBzIn+LyA3CQWztxbg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T17:49:58Z"
  mac: ENC[AES256_GCM,data:JREKmsWCf9u2/GBPBjlwD8AcWghzSButy3OjIlaaD9nS2WwailknXlFU5z6KOFqyFXpXBe1Z+/mcC+MY3FJ+wuIgPzadrjFmpQmkp7fBWhEgXy2Olb10cISjpM8g/yA9dxNt4UnDwJgSjLVT9Pai9YxMVurPE8d1Ji+SpDU7N7I=,iv:y50EiTE3F7vHNqnmTc6KAD03n2vpBscT2qY9WK7UwMM=,tag:OhGjmq3TXJATNB0PHAw7Yg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
