apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:7t5nodtXMJ/ZlgDHLF2hb5qprV2wmPNUWcAwZlowDJYBJeONv6UpJQ==,iv:hkD81MLqo0J9Yfcjto5QHk0Fs3qGiNXekcY9YPWtNrs=,tag:FWV4XOfaVF6zrmcCA79Icw==,type:str]
sops:
  age:
    - recipient: age1sg9gnvhpvlw3r7t8yey6x73w67pgsfpjd9884k773pzm72g3r39qvwq20v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMi9naWRmODA0UW1HT1JY
        d282b0RXMHhhaENHclVNbWhQQkozaDQ5Q2dRCkVUU0t1MFo2VXpRd1pnV090ZUs3
        UUN1am56VVJ6dDlnSWl1MHRkeVp0WFEKLS0tIG5GTWNzOHVOZlNXam5SejlqaUJW
        S2ZaV0pleDV0bWhTTTlQNHpMODcrN0UKl2MWrm8TAOc7frhBFloZZQOazaXy+zHD
        azKJHfyHtbmfE1AyIyANKw3yK3+MJsx5eCiqYKMFn1m6pIZYzkJ31A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T09:16:42Z"
  mac: ENC[AES256_GCM,data:7CQkcDbfc82nSVb7jHhHh+0W+Jg5WtS6+z1wXMrA+7WDt8M8KJ++lw1HKaFpNcRHJsMqVmx//khC9WVf0fklPQFoL/guQQ2N4cyTQSoQ2S6BSpeAqka1p1uRNIgchMmxSnTi3ofOMdkKhssIjv1hXM7d/BFWXazs8AI5ebjlsI8=,iv:k+AmU5tw5aG+8MPYFySMkNo9rril+zGjYOv/qRobAvk=,tag:1zETZ5eRQML5bLy8YFVHCA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
