---
ingress:
  - hostname: npmulder.dev
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
    originRequest:
      originServerName: external.npmulder.dev
  - hostname: "*.npmulder.dev"
    service: *svc
    originRequest:
      originServerName: external.npmulder.dev
  - service: http_status:404
