apiVersion: v1
kind: Service
metadata:
  name: otel-collector-external
  namespace: observability
  annotations:
    lbipam.cilium.io/ips: "10.1.2.24"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/instance: opentelemetry-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
    - name: jaeger-grpc
      port: 14250
      targetPort: 14250
      protocol: TCP
    - name: jaeger-thrift-http
      port: 14268
      targetPort: 14268
      protocol: TCP
    - name: zipkin
      port: 9411
      targetPort: 9411
      protocol: TCP
    - name: metrics
      port: 8888
      targetPort: 8888
      protocol: TCP
    - name: health-check
      port: 13133
      targetPort: 13133
      protocol: TCP
  externalTrafficPolicy: Cluster