apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-operator
  namespace: observability
spec:
  interval: 30m
  chart:
    spec:
      chart: opentelemetry-operator
      version: 0.69.0
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    manager:
      image:
        repository: ghcr.io/open-telemetry/opentelemetry-operator/opentelemetry-operator
        tag: 0.113.0
      resources:
        limits:
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 64Mi
      env:
        ENABLE_WEBHOOKS: "true"
        ENABLE_MULTI_INSTRUMENTATION: "true"
        ENABLE_APPROVERS: "true"
        ENABLE_TARGET_ALLOCATOR: "true"
        ENABLE_PROMETHEUS_CR: "true"
        ENABLE_OPAMP_BRIDGE: "true"
        ENABLE_GO_AUTO_INSTRUMENTATION: "true"
        ENABLE_PYTHON_AUTO_INSTRUMENTATION: "true"
        ENABLE_JAVA_AUTO_INSTRUMENTATION: "true"
        ENABLE_NODEJS_AUTO_INSTRUMENTATION: "true"
        ENABLE_DOTNET_AUTO_INSTRUMENTATION: "true"
        ENABLE_NGINX_AUTO_INSTRUMENTATION: "true"
        ENABLE_APACHE_AUTO_INSTRUMENTATION: "true"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
    kubeRBACProxy:
      enabled: true
      image:
        repository: gcr.io/kubebuilder/kube-rbac-proxy
        tag: v0.18.1
      resources:
        limits:
          memory: 64Mi
        requests:
          cpu: 5m
          memory: 32Mi
    admissionWebhooks:
      create: true
      failurePolicy: Fail
    nodeSelector: {}
    tolerations: []
    affinity: {}
    priorityClassName: ""
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      fsGroup: 65534