# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:PDsdA2pHIkXzQluLk1j5ENTu6b6vf8ja0gwJx+K6ZFYUzJzepA==,iv:d864lOvsVltphyXRDS57Q8CWwW/olmTpfRb1IwZmeSw=,tag:dGjl/k1i+KRZY1TYKA6HTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qt57vy74f202l635kzz7dpv3d6k6mq0qpkcnvpsrz7yn46zvdfwqdwj3se
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VFBCcGR4N0JZQTRDL3VH
            RjAwcTEvdWJIRGtmZmJKa2xINFhHNjBhbEZzCkdTdVBncmNQUGxsNDNid0tSYk1U
            bFM2bmh2WjdURnd0ekJvOU5sQXFNeU0KLS0tIEh4clkrbmJKUHk2TFljYkVHYkcr
            N3c4aXlyMk5ZYjRNYmxQN1JmVVVIVmsKyp25UkqYvWRLxNZBcCdSuLJFufLanZFx
            C5wKmZ0W9YI5LqwLCLoOdXwjgISxFihDSd6SIGbyBQKT2hQGZsKgqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-09T16:02:28Z"
    mac: ENC[AES256_GCM,data:1jkqhPutuBDj0qLzlg1FkalM+waCKUxODiIpK0ocZkuCcvmvfcc9puleg9hzsKwji4VGw5fPfZD9JSqqKL8tKJtZAOOd6xA3c9oAV0YWBFpbgk+fVy5HJfxaHzvKrInGghL6/nVl/iU2+4o1kDImKuy4gzXcxGrofcrMg2Ppies=,iv:9AaOFrO/tCdkbczeQ4YADO8ZtLPCH5blfhvy//o16Gs=,tag:QhACRhAgf021c11IlVXCRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
