# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:oWGL4yJ4cF4ckKjsYMHwOCaIfxURR18R7EGgwNXDBC69GctNrQ==,iv:AWK1R2zTsXFq6jETGojQDZWhbDcyvHNPGPZZ8zWe2tU=,tag:gWMZtr8j6Y5Q5BAQVIM1Jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qt57vy74f202l635kzz7dpv3d6k6mq0qpkcnvpsrz7yn46zvdfwqdwj3se
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDOGhDcEJqZmh6Qlh2RjFQ
            OEErU2xSay9pQ1BWeXJkTnB6TmlFeWV5NUZVCmVSMXFDZVpZRjQwWmVMUDdUR3ZQ
            eG96QXBpYjhBTitJWHFjejYvNDFabnMKLS0tIDRaYVBZTnpPY0NkckRmQUtVN2JE
            bXFkOWJSN3hHY3hIS25UV0MxZUJBRTgKqZSxYpWDAiIE0nRshDn2ZFmtsqwHH2im
            01ScXMxWBe+taISJGk+fH5mkkjhnZ3OHohCOnP+63igq1pk/FRbqsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-09T13:45:23Z"
    mac: ENC[AES256_GCM,data:RMue5vvLMleE3f9vCXbBKl7KEv/17861kA1VkwrP9iFxEltWJKugNoNQvyLHsfwL2aVISjMcxs/nwXne3uP7hW7FMFC0xg1z9zlgvonOnMNGu32rDDGMnFMvAsoomig1yzYgBqhpPd7gKCtIpTZ5dmM7LEvuxs3WyUv8+mnA21g=,iv:oWOR7JrsTO0DOGPiNZMoasCMZqKLA4hIxf08lbzmtck=,tag:BkiMvLP18b70puWnDEXqMw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
