---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app resume-website
  namespace: flux-system
spec:
  targetNamespace: resume
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: resume-namespace
  path: ./kubernetes/apps/resume/resume-website/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m