---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: npmulder-dev
spec:
  secretName: npmulder-dev-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: npmulder.dev
  dnsNames: ["npmulder.dev", "*.npmulder.dev"]
